"""Configuration and options dataclasses."""

from __future__ import annotations

import sys
from dataclasses import field
from typing import TYPE_CHECKING, Annotated, Any, Literal

from mkdocstrings import get_logger

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self


_logger = get_logger(__name__)


try:
    import pydantic

    if getattr(pydantic, "__version__", "1.").startswith("1."):
        raise ImportError  # noqa: TRY301

    if sys.version_info < (3, 10):
        try:
            import eval_type_backport  # noqa: F401
        except ImportError:
            _logger.debug(
                "Pydantic needs the `eval-type-backport` package to be installed "
                "for modern type syntax to work on Python 3.9. "
                "Deactivating Pydantic validation for Go handler options.",
            )
            raise

    from inspect import cleandoc

    from pydantic import Field as BaseField
    from pydantic.dataclasses import dataclass

    _base_url = "https://mkdocstrings.github.io/go/usage"

    def _Field(  # noqa: N802
        *args: Any,
        description: str,
        group: Literal["general", "packages", "headings"] | None = None,
        parent: str | None = None,
        **kwargs: Any,
    ) -> None:
        def _add_markdown_description(schema: dict[str, Any]) -> None:
            url = f"{_base_url}/{f'configuration/{group}/' if group else ''}#{parent or schema['title']}"
            schema["markdownDescription"] = f"[DOCUMENTATION]({url})\\n\\n{schema['description']}"

        return BaseField(
            *args,
            description=cleandoc(description),
            field_title_generator=lambda name, _: name,
            json_schema_extra=_add_markdown_description,
            **kwargs,
        )
except ImportError:
    from dataclasses import dataclass  # type: ignore[no-redef]

    def _Field(*args: Any, **kwargs: Any) -> None:  # type: ignore[misc]  # noqa: N802
        pass


if TYPE_CHECKING:
    from collections.abc import MutableMapping


_dataclass_options = {"frozen": True}
if sys.version_info >= (3, 10):
    _dataclass_options["kw_only"] = True


@dataclass(**_dataclass_options)  # type: ignore[call-overload]
class GoInputOptions:
    """Accepted input options."""

    extra: Annotated[
        dict[str, Any],
        _Field(group="general", description="Extra options."),
    ] = field(default_factory=dict)

    heading: Annotated[
        str,
        _Field(
            group="headings",
            description="A custom string to override the autogenerated heading of the root object.",
        ),
    ] = ""

    heading_level: Annotated[
        int,
        _Field(group="headings", description="The initial heading level to use."),
    ] = 2

    show_symbol_type_heading: Annotated[
        bool,
        _Field(group="headings", description="Show the symbol type in headings."),
    ] = False

    show_symbol_type_toc: Annotated[
        bool,
        _Field(group="headings", description="Show the symbol type in the Table of Contents."),
    ] = False

    toc_label: Annotated[
        str,
        _Field(
            group="headings",
            description="A custom string to override the autogenerated toc label of the root object.",
        ),
    ] = ""

    recursive: Annotated[
        bool,
        _Field(group="packages", description="Recursively collect symbols from nested directories."),
    ] = False

    include_private: Annotated[
        bool,
        _Field(group="packages", description="Include identifiers that start with a lowercase letter."),
    ] = False

    include_tests: Annotated[
        bool,
        _Field(group="packages", description="Include files ending with `_test.go`."),
    ] = False

    @classmethod
    def coerce(cls, **data: Any) -> MutableMapping[str, Any]:
        return data

    @classmethod
    def from_data(cls, **data: Any) -> Self:
        return cls(**cls.coerce(**data))


@dataclass(**_dataclass_options)  # type: ignore[call-overload]
class GoOptions(GoInputOptions):  # type: ignore[override,unused-ignore]
    """Final options passed as template context."""

    @classmethod
    def coerce(cls, **data: Any) -> MutableMapping[str, Any]:
        return super().coerce(**data)


@dataclass(**_dataclass_options)  # type: ignore[call-overload]
class GoInputConfig:
    """Go handler configuration."""

    options: Annotated[
        GoInputOptions,
        _Field(description="Configuration options for collecting and rendering objects."),
    ] = field(default_factory=GoInputOptions)

    @classmethod
    def coerce(cls, **data: Any) -> MutableMapping[str, Any]:
        return data

    @classmethod
    def from_data(cls, **data: Any) -> Self:
        return cls(**cls.coerce(**data))


@dataclass(**_dataclass_options)  # type: ignore[call-overload]
class GoConfig(GoInputConfig):  # type: ignore[override,unused-ignore]
    """Go handler configuration."""

    options: dict[str, Any] = field(default_factory=dict)  # type: ignore[assignment]

    @classmethod
    def coerce(cls, **data: Any) -> MutableMapping[str, Any]:
        return super().coerce(**data)
